### ISSUE TITLE
best way handling sub-crates

### ISSUE THREAD

**Issue by chpio** [rust-fcp/rust-fcp-cryptoauth#2]
hi,

i wonder what's the best way to handle sub crates. so i tried workspaces, it seems to work pretty nice. (disclaimer: i never worked with workspaces before)

how to use ws:
1. `mkdir fcp`
2. clone all sub-creates into the fcp dir (i renamed them eg *rust-fcp-switching* to *switching*)
3. create a Cargo.toml file in fcp:
```toml
[workspace]
members = ["cryptoauth", "switch", "switching"]

[replace]
"fcp_cryptoauth:0.1.0" = { path = 'cryptoauth' }
"fcp_switching:0.1.0" = { path = 'switching' }
```

pros:
* less rebuilds (all creates share one build dir)
* you work with the local source code without the need to add path-deps in your sub-crate Cargo.toml files

cons:
* ?

what do you think about workspaces?
